name: "ttbar_hadronic_hdampDown"
locations:
    - "/scratch/data/tZqSkimsRun2017/ttbar_hadronic_hdampDOWN/"
total_events: 27117982
cross_section: 377.96
mc: true
histogram: "ttbar"
colour: "#cc0000"
label: "t#bar{t}"
plot_type: "f"
